# LLM Compose configuration
# sudo podman run --rm --device nvidia.com/gpu=all --security-opt=label=disable ubuntu nvidia-smi -L
# This works to show the GPU inside a container

volumes:
  ollama-data:
  webui-data:
  n8n-data:

networks:
  proxy:
    external: true
  ollama-network:
    external: false

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    networks:
      - ollama-network
    devices:
      - nvidia.com/gpu=all
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    volumes:
      - webui-data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - ollama-network
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama-ui.rule=Host(`${OLLAMA_UI_DOMAIN}`)"
      - "traefik.http.routers.ollama-ui.entrypoints=websecure"
      - "traefik.http.routers.ollama-ui.tls=true"
      - "traefik.http.services.ollama-ui.loadbalancer.server.port=8080"
      - "traefik.http.routers.ollama-ui.tls.certresolver=cloudflare"
      - "traefik.docker.network=proxy"

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      - N8N_HOST=${N8N_DOMAIN}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${N8N_DOMAIN}/
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - GENERIC_TIMEZONE=America/New_York
      - TZ=America/New_York
      # Ollama connection using internal net ollama-network
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - n8n-data:/home/node/.n8n
    depends_on:
      - ollama
    networks:
      - ollama-network
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`${N8N_DOMAIN}`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.routers.n8n.tls.certresolver=cloudflare"
      - "traefik.docker.network=proxy"
